[package]
name = "nodescale-invitation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chrono.workspace = true
nodescale-domain = { path = "../nodescale-domain" }
nodescale-provider = { path = "../nodescale-provider" }
nodescale-state = { path = "../nodescale-state" }

[dev-dependencies]
async-trait.workspace = true
nodescale-provider-fake = { path = "../nodescale-provider-fake" }
tempfile = "3"
tokio.workspace = true

[lints]
workspace = true
